---
apiVersion: v1
kind: Namespace
metadata:
  name: microservice

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-microservice
  namespace: microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: database-microservice
  template:
    metadata:
      labels:
        app.kubernetes.io/name: database-microservice
    spec:
      containers:
        - name: database-service-container
          image: registry.secd/microservices/database_service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
      imagePullSecrets:
        - name: regcred

---
apiVersion: v1
kind: Service
metadata:
  name: database-microservice
  namespace: microservice
spec:
  type: NodePort
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      nodePort: 30000  # You can specify a port or let Kubernetes assign one
  selector:
    app.kubernetes.io/name: database-microservice
