{
    path:
        {
            type: "dict",
            schema:
            {
                repoPath: { type: "string", required: true },
                cachePath: { type: "string", required: true },
            },
        },
    gitlab:
        {
            type: "dict",
            schema:
                {
                    url: { type: "string", required: true },
                    token: { type: "string", required: true },
                    secret: { type: "string", required: true },
                    username: { type: "string", required: true },
                    password: { type: "string", required: true },
                },
        },
    keycloak:
        {
        type: "dict",
        schema:
            {
                url: { type: "string", required: true },
                realm: { type: "string", required: true },
                username: { type: "string", required: true },
                password: { type: "string", required: true },
                gitlab:
                {
                    type: "dict",
                    schema:
                    {
                        client_id: { type: "string", required: true },
                        client_secret: { type: "string", required: true },
                    },
                },
                database-service:
                {
                    type: "dict",
                    schema:
                    {
                        client_id: { type: "string", required: true },
                        client_secret: { type: "string", required: true },
                    },
                },
                admin-cli:
                {
                    type: "dict",
                    schema:
                    {
                        client_id: { type: "string", required: true },
                        client_secret: { type: "string", required: true },
                    },
                },
            },
        },
    db: {
        type: "dict",
        schema:
            {
                mysql:
                    {
                        type: "dict",
                        schema:
                            {
                                host: {type: 'string', required: true},
                                username: {type: 'string', required: true},
                                password: {type: 'string', required: true},
                            },
                        },
            },
    },
    registry:
        {
            type: "dict",
            schema:
                {
                    url: { type: "string", required: true },
                    project: { type: "string", required: true },
                    username: { type: "string", required: true },
                    password: { type: "string", required: true },
                },
        },
    k8s:
        {
            type: "dict",
            schema:
                {
                    configPath: { type: "string", required: true },
                    pvcPath: { type: "string", required: true },
                },
        },
}
